### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by 757312847** [ABadCandy/BaiDuBigData19-URFC#2]
报错的库imgaug==0.2.8，torch==1.1.0，我使用的是3.7，运行的时候，不支持。请问您的具体的运行环境？

具体报错如下：
Traceback (most recent call last):
  File "multimain.py", line 249, in <module>
    main()
  File "multimain.py", line 212, in main
    train_metrics = train(train_loader,model,criterion,optimizer,epoch,val_metrics,best_results,start)
  File "multimain.py", line 56, in train
    for i,(images,visit,target) in enumerate(train_loader):
  File "D:\computer_language\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "D:\computer_language\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "D:\computer_language\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\computer_language\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "E:\大数据\2019大数据竞赛初赛数据集\BaiDuBigData19-URFC-master\multimodal.py", line 62, in __getitem__
    X = self.augumentor(X)
  File "E:\大数据\2019大数据竞赛初赛数据集\BaiDuBigData19-URFC-master\multimodal.py", line 99, in augumentor
    image_aug = augment_img.augment_image(image)
  File "D:\computer_language\anaconda3\lib\site-packages\imgaug\augmenters\meta.py", line 405, in augment_image
    ia.do_assert(image.ndim in [2, 3],
AttributeError: 'NoneType' object has no attribute 'ndim'

**Comment by ABadCandy** [comment]
@757312847 你好，我用的是Anaconda的python3.6.4，可能3.7版本较新所以报错的那两个库还不支持把，另外我是在服务器的docker容器中跑的，windows上也没测试过，而且建议代码运行路径最好不要有中文O.O

**Comment by 757312847** [comment]
好的，谢谢啦------------------ 原始邮件 ------------------
发件人: "Hao Tang"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 上午9:27
收件人: "ABadCandy/BaiDuBigData19-URFC"<BaiDuBigData19-URFC@noreply.github.com>;
抄送: "757312847"<757312847@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ABadCandy/BaiDuBigData19-URFC] 运行环境 (#2)



@757312847 你好，我用的是Anaconda的python3.6.4，可能3.7版本较新所以报错的那两个库还不支持把，另外我是在&#x670D;务器的docker容器中跑的，windows上也没测试过，而且建议代码运行路径最好不要有中文O.O
 
&mdash;

**Comment by lzyplayer** [comment]
@ABadCandy 在一台Mac上遇到了同样的问题，同时Python版本也是3.6，不过还是谢谢大佬的分享
