### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by JingXiaolun** [ABadCandy/BaiDuBigData19-URFC#4]
Traceback (most recent call last):
  File "multimain.py", line 249, in <module>
    main()
  File "multimain.py", line 212, in main
    train_metrics = train(train_loader,model,criterion,optimizer,epoch,val_metrics,best_results,start)
  File "multimain.py", line 62, in train
    output = model(images,visit)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/csu/新加卷/AI Competition/Competition/一带一路国际大数据竞赛/初赛赛题/方案二/multimodal.py", line 275, in forward
    x_vis=self.visit_model(x_vis)
  File "/home/csu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/csu/新加卷/AI Competition/Competition/一带一路国际大数据竞赛/初赛赛题/方案二/multimodal.py", line 218, in forward
    out = F.avg_pool2d(out, 4)
RuntimeError: Given input size: (2432x4x3). Calculated output size: (2432x1x0). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:63
This problem has confused me for a few days,I hope you can offer me a solution to this problem,thanks a lot.

**Comment by ABadCandy** [comment]
@1csu Sorry for being so late to reply for personal reasons, have you solved this problem yet?
It seems that input image size of visit_model is too small and the pretrained Imagenet models are not suitable for such small size input.
